FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt .
RUN python -m pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT=8000
EXPOSE $PORT

CMD ["sh", "-c", "python manage.py runserver 0.0.0.0:$PORT"]